apiVersion: v1
baseDomain: ocp.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16

platform:
  none: {}

fips: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNGRjYjY1NzA1OTBmNDM3ZWFmNDQ4YzFkNzU0OTRhZDc6MDFPTjhZTzNBSkxVREZBRUo5V1dZUklUQlNOME1aVFhVSE1QTDMwQTNLMks3MDM5ODU0UlJLNjY1UkFIUVBVQQ==","email":"pratul.singh@hpe.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNGRjYjY1NzA1OTBmNDM3ZWFmNDQ4YzFkNzU0OTRhZDc6MDFPTjhZTzNBSkxVREZBRUo5V1dZUklUQlNOME1aVFhVSE1QTDMwQTNLMks3MDM5ODU0UlJLNjY1UkFIUVBVQQ==","email":"pratul.singh@hpe.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTA3YWZhMTdjLTA1MDktNGUyMi1hMDllLTc5NzFkYjE2MTcxODpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlOalUyTURBME1XUXlORFUwT1dFM09UaGtZV1EwWVdNd05HRXlNVGd5WlNKOS54Q1hZUjZ4SG82cENxNEJyRjhGUWdXbm9CNGFtNkgzUG4yUWcxajJBeEV5OEdwM3lrSGVUM1IxU3hsV2xTWVk2VjJqZGI3Szk5VE9kM0Q3bEtTWllMRzZhbUJSWUxjZnZERldhQy12bXlwSVJlZ3llNjlRVmRFTkd6SE90ak5iYnRXTHF2OWxmMmFVRGdBSWlPQ3U1cHM3cHZfai1QcXlOZGxsQlV1MHBMT0NpWWRrZUJ1WmhGRFBnSG5QWmw0dlBUanV2WWhUSF9Sa0ZOTU1kb05NdTdpSE51N2JSckRWeFBxMFk3SGtBb3Mwb0Q4TkdMMEw1bkpmOENhMnM1ZTRwOEl5OVlqanBYUEFESmp3NnE5X3BjaG5BN05hLXFXdXhxaEhmYzM2M2Vxa0o4UDdFeWNCeXRUVHhXQVE4cFcteGhPWW9vTzg3UE1Uc25JX1BQWFUyTmpoWjVRS3lGekt3N0t1X2dXQ2laMXVoQzZrS05EdElPSDJIY1Jpb0k2RjBFT2hBY2lDYjhvSXZqT3h2MEczek9XM3V1YVJZUkFCV1NEMF9LUmlfd2RoaVZfa2JOM3NaT0I1b2RfSDZ5dDN1b0VlZ0xlYnRvajNBU3J1UzBQbEFiT2wzd0RndGxfcTJvNkVxWkJqYXJVanN4R1Z0ZVJtekgzbGV6T3gtNHNkVVY3d2VxMjlEaWd5SlhTWi10WkNTSGFTMzhwQUUzQ2QyRUFCOW4wdElxQWVzYThaWFllYkFKd2lDb1gzcEVYbktsNndZamxDNWlCQmVHMnlXMWhQQzExU083aFpzYXdoMXdLVW8yRjNzS0lKbTZpTDYtam0yUDVFRUxJVnRHTXNsTFBfNUlhdi1Qa0pFS3JkY1BJVW1vSU5xMmJndjZOakFkSVZyU0dFQzJMQQ==","email":"pratul.singh@hpe.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTA3YWZhMTdjLTA1MDktNGUyMi1hMDllLTc5NzFkYjE2MTcxODpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlOalUyTURBME1XUXlORFUwT1dFM09UaGtZV1EwWVdNd05HRXlNVGd5WlNKOS54Q1hZUjZ4SG82cENxNEJyRjhGUWdXbm9CNGFtNkgzUG4yUWcxajJBeEV5OEdwM3lrSGVUM1IxU3hsV2xTWVk2VjJqZGI3Szk5VE9kM0Q3bEtTWllMRzZhbUJSWUxjZnZERldhQy12bXlwSVJlZ3llNjlRVmRFTkd6SE90ak5iYnRXTHF2OWxmMmFVRGdBSWlPQ3U1cHM3cHZfai1QcXlOZGxsQlV1MHBMT0NpWWRrZUJ1WmhGRFBnSG5QWmw0dlBUanV2WWhUSF9Sa0ZOTU1kb05NdTdpSE51N2JSckRWeFBxMFk3SGtBb3Mwb0Q4TkdMMEw1bkpmOENhMnM1ZTRwOEl5OVlqanBYUEFESmp3NnE5X3BjaG5BN05hLXFXdXhxaEhmYzM2M2Vxa0o4UDdFeWNCeXRUVHhXQVE4cFcteGhPWW9vTzg3UE1Uc25JX1BQWFUyTmpoWjVRS3lGekt3N0t1X2dXQ2laMXVoQzZrS05EdElPSDJIY1Jpb0k2RjBFT2hBY2lDYjhvSXZqT3h2MEczek9XM3V1YVJZUkFCV1NEMF9LUmlfd2RoaVZfa2JOM3NaT0I1b2RfSDZ5dDN1b0VlZ0xlYnRvajNBU3J1UzBQbEFiT2wzd0RndGxfcTJvNkVxWkJqYXJVanN4R1Z0ZVJtekgzbGV6T3gtNHNkVVY3d2VxMjlEaWd5SlhTWi10WkNTSGFTMzhwQUUzQ2QyRUFCOW4wdElxQWVzYThaWFllYkFKd2lDb1gzcEVYbktsNndZamxDNWlCQmVHMnlXMWhQQzExU083aFpzYXdoMXdLVW8yRjNzS0lKbTZpTDYtam0yUDVFRUxJVnRHTXNsTFBfNUlhdi1Qa0pFS3JkY1BJVW1vSU5xMmJndjZOakFkSVZyU0dFQzJMQQ==","email":"pratul.singh@hpe.com"}}}'
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEKUcDwO+OWlWauA1ev2UH2P7zizyUFs2FfdNl5GyprC root@ocp4-services.ocp.local'
